project:
  type: website
  output-dir: docs

website:
  title: "Baobao Zhang"
  favicon: img/drawing.jpg
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching + Mentoring
      - href: engagement.qmd
        text: Public Engagement

format:
  html:
    theme: cosmo
    backgroundcolor: "#F0EDEE"
    css: styles.css
    toc: true

editor: visual

